/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kumanyaev.my_rent;

import javax.swing.JTextField;

/**
 *
 * @author 6PATyCb
 */
public class MainJFrame extends javax.swing.JFrame {

    private final RentBean rentBean = Serializer.deserialize(new RentBean());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        loadValues();
    }

    private void loadValues() {
        tarifHotField.setText(RentBean.format(rentBean.getTarifWaterHot()));
        prevHotField.setText(RentBean.format(rentBean.getPrevousWaterHot()));
        currHotField.setText(RentBean.format(rentBean.getCurrentWaterHot()));

        tarifColdField.setText(RentBean.format(rentBean.getTarifWaterCold()));
        prevColdField.setText(RentBean.format(rentBean.getPrevousWaterCold()));
        currColdField.setText(RentBean.format(rentBean.getCurrentWaterCold()));

        tarifWaterOutField.setText(RentBean.format(rentBean.getTarifWaterOut()));
        prevWaterOutField.setText(RentBean.format(rentBean.getPrevousWaterOut()));
        currWaterOutField.setText(RentBean.format(rentBean.getCurrentWaterOut()));

        tarifElectroField.setText(RentBean.format(rentBean.getTarifElectro()));
        prevElectroField.setText(RentBean.format(rentBean.getPrevousElectro()));
        currElectroField.setText(RentBean.format(rentBean.getCurrentElectro()));

        tarifInetField.setText(RentBean.format(rentBean.getTarifInet()));

        tarifMainField.setText(RentBean.format(rentBean.getTarifMain()));
        factPayField.setText(RentBean.format(rentBean.getFactPay()));
        prevChangeField.setText(RentBean.format(rentBean.getPrevChange()));
        showMainSummCheckBox.setSelected(rentBean.isShowMainSumm());
    }

    private float toFloat(String text) {
        try {
            return Float.valueOf(text.replaceAll("[^,.\\d]", "").replaceAll(",", "."));
        } catch (NumberFormatException e) {
            return 0;
        }

    }

    private void selectTextValue(JTextField jTextField) {
        if (jTextField == null) {
            return;
        }
        jTextField.selectAll();
    }

    private void save() {
        System.out.println("Сохраняем данные");
        Serializer.serialize(rentBean);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calcButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        prevHotField = new javax.swing.JTextField();
        prevColdField = new javax.swing.JTextField();
        prevWaterOutField = new javax.swing.JTextField();
        tarifHotField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tarifColdField = new javax.swing.JTextField();
        tarifWaterOutField = new javax.swing.JTextField();
        tarifElectroField = new javax.swing.JTextField();
        tarifInetField = new javax.swing.JTextField();
        prevElectroField = new javax.swing.JTextField();
        currHotField = new javax.swing.JTextField();
        currColdField = new javax.swing.JTextField();
        currWaterOutField = new javax.swing.JTextField();
        currElectroField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        toPrevButton = new javax.swing.JButton();
        tarifMainField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        factPayField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prevChangeField = new javax.swing.JTextField();
        toPayedButton = new javax.swing.JButton();
        showMainSummCheckBox = new javax.swing.JCheckBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Расчет тарифов");
        setResizable(false);

        calcButton.setText("Посчитать");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Горячая");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Холодная");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Водоотвод");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Тариф");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Электричество");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Прошлый месяц");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Текущий месяц");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Интернет");

        prevHotField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prevHotField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prevHotFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prevHotFieldFocusLost(evt);
            }
        });

        prevColdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prevColdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prevColdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prevColdFieldFocusLost(evt);
            }
        });

        prevWaterOutField.setEditable(false);
        prevWaterOutField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tarifHotField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifHotField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifHotFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifHotFieldFocusLost(evt);
            }
        });

        tarifColdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifColdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifColdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifColdFieldFocusLost(evt);
            }
        });

        tarifWaterOutField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifWaterOutField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifWaterOutFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifWaterOutFieldFocusLost(evt);
            }
        });

        tarifElectroField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifElectroField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifElectroFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifElectroFieldFocusLost(evt);
            }
        });

        tarifInetField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifInetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifInetFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifInetFieldFocusLost(evt);
            }
        });

        prevElectroField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prevElectroField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prevElectroFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prevElectroFieldFocusLost(evt);
            }
        });

        currHotField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currHotField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currHotFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                currHotFieldFocusLost(evt);
            }
        });

        currColdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currColdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currColdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                currColdFieldFocusLost(evt);
            }
        });

        currWaterOutField.setEditable(false);
        currWaterOutField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        currElectroField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currElectroField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currElectroFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                currElectroFieldFocusLost(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        toPrevButton.setText("В прошлый");
        toPrevButton.setToolTipText("Сделать данные текущего месяца данными прошлого месяца");
        toPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPrevButtonActionPerformed(evt);
            }
        });

        tarifMainField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarifMainField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifMainFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifMainFieldFocusLost(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Осн. аренда");

        factPayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        factPayField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                factPayFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                factPayFieldFocusLost(evt);
            }
        });
        factPayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factPayFieldActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Остаток:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Оплачено:");

        prevChangeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prevChangeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prevChangeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prevChangeFieldFocusLost(evt);
            }
        });
        prevChangeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevChangeFieldActionPerformed(evt);
            }
        });

        toPayedButton.setText("В оплачено");
        toPayedButton.setToolTipText("Занести в поле \"Оплачено\" сумму, требуемую к оплате");
        toPayedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPayedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toPrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toPayedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prevHotField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prevColdField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prevWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prevElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prevChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifHotField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifColdField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifInetField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarifMainField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(currHotField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(currColdField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(currWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(currElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(factPayField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tarifHotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifColdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifInetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifMainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prevHotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevColdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(prevChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(currHotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currColdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currWaterOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currElectroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factPayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toPrevButton)
                    .addComponent(toPayedButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showMainSummCheckBox.setText("Показывать основную сумму");
        showMainSummCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMainSummCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcButton)
                        .addGap(18, 18, 18)
                        .addComponent(showMainSummCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcButton)
                    .addComponent(showMainSummCheckBox))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        save();
        jTextArea1.setText(rentBean.doAllCalculation());
    }//GEN-LAST:event_calcButtonActionPerformed

    private void tarifHotFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifHotFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifWaterHot(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifHotFieldFocusLost

    private void prevHotFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevHotFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setPrevousWaterHot(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_prevHotFieldFocusLost

    private void currHotFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currHotFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setCurrentWaterHot(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_currHotFieldFocusLost

    private void tarifColdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifColdFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifWaterCold(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifColdFieldFocusLost

    private void currColdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currColdFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setCurrentWaterCold(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_currColdFieldFocusLost

    private void tarifWaterOutFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifWaterOutFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifWaterOut(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifWaterOutFieldFocusLost

    private void prevColdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevColdFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setPrevousWaterCold(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_prevColdFieldFocusLost

    private void tarifInetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifInetFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifInet(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifInetFieldFocusLost

    private void tarifElectroFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifElectroFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifElectro(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifElectroFieldFocusLost

    private void prevElectroFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevElectroFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setPrevousElectro(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_prevElectroFieldFocusLost

    private void currElectroFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currElectroFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setCurrentElectro(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_currElectroFieldFocusLost

    private void toPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPrevButtonActionPerformed
        rentBean.currentToPrev();
        loadValues();
    }//GEN-LAST:event_toPrevButtonActionPerformed

    private void tarifHotFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifHotFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifHotFieldFocusGained

    private void prevHotFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevHotFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_prevHotFieldFocusGained

    private void currHotFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currHotFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_currHotFieldFocusGained

    private void tarifColdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifColdFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifColdFieldFocusGained

    private void prevColdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevColdFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_prevColdFieldFocusGained

    private void currColdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currColdFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_currColdFieldFocusGained

    private void tarifWaterOutFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifWaterOutFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifWaterOutFieldFocusGained

    private void tarifElectroFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifElectroFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifElectroFieldFocusGained

    private void prevElectroFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevElectroFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_prevElectroFieldFocusGained

    private void currElectroFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currElectroFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_currElectroFieldFocusGained

    private void tarifInetFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifInetFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifInetFieldFocusGained

    private void tarifMainFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifMainFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_tarifMainFieldFocusGained

    private void tarifMainFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifMainFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setTarifMain(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_tarifMainFieldFocusLost

    private void factPayFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_factPayFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_factPayFieldFocusGained

    private void factPayFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_factPayFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setFactPay(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_factPayFieldFocusLost

    private void factPayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factPayFieldActionPerformed

    }//GEN-LAST:event_factPayFieldActionPerformed

    private void prevChangeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevChangeFieldFocusGained
        JTextField sourceField = (JTextField) evt.getSource();
        selectTextValue(sourceField);
    }//GEN-LAST:event_prevChangeFieldFocusGained

    private void prevChangeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prevChangeFieldFocusLost
        JTextField sourceField = (JTextField) evt.getSource();
        rentBean.setPrevChange(toFloat(sourceField.getText()));
        loadValues();
    }//GEN-LAST:event_prevChangeFieldFocusLost

    private void prevChangeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevChangeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevChangeFieldActionPerformed

    private void toPayedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPayedButtonActionPerformed
        rentBean.setFactPay(rentBean.calculatePaymentValue());
        loadValues();
    }//GEN-LAST:event_toPayedButtonActionPerformed

    private void showMainSummCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMainSummCheckBoxActionPerformed
        boolean isShowMainSumm = showMainSummCheckBox.isSelected();
        rentBean.setShowMainSumm(isShowMainSumm);
    }//GEN-LAST:event_showMainSummCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame mainJFrame = new MainJFrame();
                mainJFrame.setLocationRelativeTo(null);
                mainJFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JTextField currColdField;
    private javax.swing.JTextField currElectroField;
    private javax.swing.JTextField currHotField;
    private javax.swing.JTextField currWaterOutField;
    private javax.swing.JTextField factPayField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField prevChangeField;
    private javax.swing.JTextField prevColdField;
    private javax.swing.JTextField prevElectroField;
    private javax.swing.JTextField prevHotField;
    private javax.swing.JTextField prevWaterOutField;
    private javax.swing.JCheckBox showMainSummCheckBox;
    private javax.swing.JTextField tarifColdField;
    private javax.swing.JTextField tarifElectroField;
    private javax.swing.JTextField tarifHotField;
    private javax.swing.JTextField tarifInetField;
    private javax.swing.JTextField tarifMainField;
    private javax.swing.JTextField tarifWaterOutField;
    private javax.swing.JButton toPayedButton;
    private javax.swing.JButton toPrevButton;
    // End of variables declaration//GEN-END:variables
}
